Files created
lwwwrjke-org/po-5-wt pull request #12
Opened 2021-03-17 07:28 UTC by PAUVLE

2021-03-17 21:33 UTC, Pavel-Soloduha requested changes
Перепроверь написание аттрибутов.

2021-03-18 20:40 UTC, Pavel-Soloduha requested changes

2021-03-18 20:40 UTC, Pavel-Soloduha commented on Reports/Vasilyuk_Pavel/lab1/Lab1.html
> +                        <input name="prlang" type="text" size="80" placeholder="Your anwser" required maxlength="50">
Ведь правильно было - зачем сменил?)

2021-03-18 21:31 UTC, PAUVLE commented on Reports/Vasilyuk_Pavel/lab1/Lab1.html
> +                        <input name="prlang" type="text" size="80" placeholder="Your anwser" required maxlength="50">
Вернул

2021-03-22 06:26 UTC, Pavel-Soloduha approved these changes

2021-03-22 10:28 UTC, merged