Lab1/radionchik svetlana
lwwwrjke-org/po-5-wt pull request #2
Opened 2021-02-28 11:37 UTC by Carrife

2021-03-02 23:00 UTC, Pavel-Soloduha requested changes
CSS конечно красивый, но есть вопросы за адаптивность, нужна она или нет @lwwwr ?

У меня на Ubuntu 20.04 Firefox 86.0 такая "красота"
![image](https://user-images.githubusercontent.com/5824148/109726558-fb4e8b80-7bc3-11eb-8b00-c8accf59f879.png)

2021-03-02 23:00 UTC, Pavel-Soloduha commented on Reports/Radionchik_Svetlana/lab1/lab1.html
> +                <br><input class="form_input" placeholder=" "><br>
А чего не использовать значение сразу в <input placeholder=""/>?

2021-03-02 23:00 UTC, Pavel-Soloduha commented on Reports/Radionchik_Svetlana/lab1/lab1.html
> +                <label class="form_label_style">Please describe your favorite programming language<label class="form_label_starstyle">*</label></label>
Тот же самый вопрос за placeholder vs label.
И чего нету ограничения по минимальному количеству символов как написано в лабе?

2021-03-02 23:00 UTC, Pavel-Soloduha commented on Reports/Radionchik_Svetlana/lab1/lab1.html
> +                <input class="form_input" placeholder=" "><br>
Вроде можно календарь и по красивее сделать.

2021-03-03 01:39 UTC, lwwwr commented
@Pavel-Soloduha пущай будет

2021-03-15 06:45 UTC, lwwwr approved these changes

2021-03-15 07:24 UTC, merged