lab2/Ignatyuk_Angrey : Added lab2
lwwwrjke-org/po-5-wt pull request #20
Opened 2021-03-17 18:46 UTC by yallknows

2021-03-17 21:48 UTC, Pavel-Soloduha requested changes

2021-03-17 21:48 UTC, Pavel-Soloduha commented on Reports/Ignatyuk_Andrey/lab2/index.html
> +        <script src="task_4.js" type="text/javascript"></script>
2016-02-31 -> Среда, звучит неправильно

2021-03-17 21:48 UTC, Pavel-Soloduha commented on Reports/Ignatyuk_Andrey/lab2/index.html
> +        <script src="task_3.js" type="text/javascript"></script>
При вводе 0 выводит -1

2021-03-18 07:27 UTC, yallknows commented
Исправлены ошибки

2021-03-18 20:57 UTC, Pavel-Soloduha approved these changes

2021-03-18 21:19 UTC, merged