Lab2 for checking
lwwwrjke-org/po-5-wt pull request #4
Opened 2021-03-01 06:50 UTC by Carrife

2021-03-02 23:11 UTC, Pavel-Soloduha requested changes

2021-03-02 23:11 UTC, Pavel-Soloduha commented on Reports/Radionchik_Svetlana/lab2/Lab2.html
> +    <h1>Задание 1</h1>
Введи как первое число 12 и как второе - 5.

2021-03-02 23:11 UTC, Pavel-Soloduha commented on Reports/Radionchik_Svetlana/lab2/script4.js
> +    let date = new Date(2016, month-1, day);
А что насчёт 30 февраля?

2021-03-15 07:01 UTC, lwwwr approved these changes

2021-03-15 07:31 UTC, merged