lab2/Valchuk_Andrey : made lab2
lwwwrjke-org/po-5-wt pull request #7
Opened 2021-03-15 07:50 UTC by AndreyValchuk

2021-03-15 08:13 UTC, lwwwr requested changes

2021-03-15 08:13 UTC, lwwwr commented on Reports/Valchuk_Andrey/lab2/index.html
> +<!DOCTYPE html>
не в ту ветку пулл-реквест

2021-03-15 08:13 UTC, lwwwr commented on Reports/Valchuk_Andrey/lab2/index.html
> +    <script src="script1.js"></script>
скриптецы циклично выполняются на на странице. сделать одноразовый запуск

2021-03-15 08:13 UTC, lwwwr commented on Reports/Valchuk_Andrey/lab2/index.html
> +    <script src="script3.js"></script>
- нету вводного сообщения, непонятно что делать.
- падает при вводе числа ноль. сделать обработчик

2021-03-15 08:13 UTC, lwwwr commented on Reports/Valchuk_Andrey/lab2/index.html
> +    <script src="script4.js"></script>
- нету вводного сообщения, непонятно что делать.

2021-03-17 20:20 UTC, Pavel-Soloduha approved these changes

2021-03-18 16:18 UTC, merged