Lab1/knysh kiryl
lwwwrjke-org/po-5-wt pull request #8
Opened 2021-03-16 21:29 UTC by 10k20

2021-03-17 21:28 UTC, Pavel-Soloduha requested changes

2021-03-17 21:28 UTC, Pavel-Soloduha commented on Reports/Knysh_Kiryl/lab1/index.html
> +                <input type="text" class="text" placeholder="Your answer..">
Где ограничение по количеству символов как было в задании лабы?

2021-03-17 21:28 UTC, Pavel-Soloduha commented on Reports/Knysh_Kiryl/lab1/index.html
> +                <input type="file">
А где загрузка файла?

2021-03-21 13:37 UTC, 10k20 commented
Исправлены ошибки

2021-03-22 08:56 UTC, Pavel-Soloduha requested changes

2021-03-22 08:56 UTC, Pavel-Soloduha commented on Reports/Knysh_Kiryl/lab1/index.html
> +                <div class="label">Please fill your name</div>
Где ограничение по количеству символов как было в задании лабы? Там ведь было в описании поля про не менее чем 50 символов.

2021-03-26 18:43 UTC, Pavel-Soloduha approved these changes

2021-04-05 06:27 UTC, merged